import { Project, Service, Testimonial, NavItem } from '@/types'

export const navItems: NavItem[] = [
  { label: 'Home', href: '/' },
  { label: 'About', href: '/about' },
  { label: 'Services', href: '/services' },
  { label: 'Work', href: '/work' },
  { label: 'Contact', href: '/contact' },
]

export const projects: Project[] = [
  {
    id: '1',
    title: 'Cinematic Wedding Film',
    category: 'Wedding',
    description: 'A breathtaking cinematic wedding film capturing every emotion with Hollywood-grade color grading and aerial cinematography.',
    thumbnail: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=800&q=80',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    tags: ['Premiere Pro', 'After Effects', 'Color Grading', 'Aerial'],
    year: 2024,
    featured: true,
  },
  {
    id: '2',
    title: 'Brand Story Campaign',
    category: 'Commercial',
    description: 'Dynamic brand storytelling video with kinetic typography and motion graphics for a lifestyle brand.',
    thumbnail: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=800&q=80',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    tags: ['Motion Graphics', 'After Effects', 'Color Grade'],
    year: 2024,
    featured: true,
  },
  {
    id: '3',
    title: 'Destination Pre-Wedding',
    category: 'Pre-Wedding',
    description: 'Stunning pre-wedding shoot at golden hour with cinematic transitions and emotional storytelling.',
    thumbnail: 'https://images.unsplash.com/photo-1529636444744-adffc9135a5e?w=800&q=80',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    tags: ['Cinematic', 'Drone', 'Premiere Pro'],
    year: 2024,
    featured: true,
  },
  {
    id: '4',
    title: 'Corporate Documentary',
    category: 'Corporate',
    description: 'Professional corporate documentary showcasing company values and team culture with professional-grade editing.',
    thumbnail: 'https://images.unsplash.com/photo-1576267423429-569309b31e84?w=800&q=80',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    tags: ['Documentary', 'Interview', 'Corporate'],
    year: 2023,
  },
  {
    id: '5',
    title: 'Music Video Production',
    category: 'Music Video',
    description: 'High-energy music video with VFX, color grading and creative cinematography matching the artist\'s vision.',
    thumbnail: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&q=80',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    tags: ['VFX', 'After Effects', 'Music'],
    year: 2023,
  },
  {
    id: '6',
    title: 'Fashion Reel',
    category: 'Fashion',
    description: 'Editorial fashion video with slow motion, dramatic lighting and contemporary editing style for social media.',
    thumbnail: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    tags: ['Fashion', 'Slow-Mo', 'Social Media'],
    year: 2023,
  },
  {
    id: '7',
    title: 'Real Estate Showcase',
    category: 'Real Estate',
    description: 'Luxury property showcase with drone footage, smooth transitions, and professional color treatment.',
    thumbnail: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    tags: ['Drone', 'Real Estate', 'Aerial'],
    year: 2024,
  },
  {
    id: '8',
    title: 'Product Launch Film',
    category: 'Commercial',
    description: 'High-impact product launch video combining live action, motion graphics and cinematic sound design.',
    thumbnail: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    tags: ['Product', 'VFX', 'Commercial'],
    year: 2023,
  },
]

export const services: Service[] = [
  {
    id: '1',
    title: 'Cinematic Video Shoot',
    description: 'Professional cinematic video production with Hollywood-grade equipment, creative direction, and expert lighting for any occasion.',
    icon: '🎬',
    features: [
      'Professional Camera Setup',
      'Cinematic Lighting',
      'Gimbal & Stabilized Shots',
      'Drone / Aerial Footage',
      'Multi-Camera Production',
    ],
    tools: ['Sony A7 Series', 'DJI Ronin', 'DJI Drone', 'Aputure Lights'],
  },
  {
    id: '2',
    title: 'Video Editing',
    description: 'Advanced video editing with seamless transitions, rhythm cuts, storytelling pacing, and professional sound design that brings your vision to life.',
    icon: '✂️',
    features: [
      'Professional Color Grading',
      'Seamless Transitions',
      'Sound Design & Mixing',
      'Subtitle & Caption',
      'Multi-format Export',
    ],
    tools: ['Adobe Premiere Pro', 'DaVinci Resolve', 'Audition'],
  },
  {
    id: '3',
    title: 'After Effects & VFX',
    description: 'Stunning visual effects, motion graphics, title animations and cinematic effects using industry-standard After Effects workflows.',
    icon: '✨',
    features: [
      'Kinetic Typography',
      'Particle Effects',
      'Green Screen / VFX',
      'Logo Animation',
      'Cinematic Overlays',
    ],
    tools: ['Adobe After Effects', 'Element 3D', 'Trapcode Suite'],
  },
  {
    id: '4',
    title: 'Wedding Films',
    description: 'Heartfelt, cinematic wedding films that capture every precious moment — from the nervous excitement to the purest joy — told as a beautiful story.',
    icon: '💍',
    features: [
      'Full Day Coverage',
      'Highlight Reel',
      'Same-Day Edit',
      'Teaser Delivery',
      'Cinematic Storytelling',
    ],
    tools: ['Premiere Pro', 'After Effects', 'Color Grading'],
  },
  {
    id: '5',
    title: 'Reels & Social Content',
    description: 'Scroll-stopping Instagram reels, YouTube shorts and social media content with trending transitions and music sync for maximum engagement.',
    icon: '📱',
    features: [
      'Trending Transitions',
      'Beat-Sync Editing',
      'Platform Optimization',
      'Aspect Ratio Variants',
      'Caption Animation',
    ],
    tools: ['Premiere Pro', 'After Effects', 'CapCut Pro'],
  },
  {
    id: '6',
    title: 'Corporate & Brand Videos',
    description: 'Professional brand documentaries, promotional videos and corporate content that communicate your brand story with visual excellence.',
    icon: '🏢',
    features: [
      'Brand Documentary',
      'Product Showcase',
      'Testimonial Videos',
      'Event Coverage',
      'Internal Communications',
    ],
    tools: ['Premiere Pro', 'After Effects', 'Audition'],
  },
]

export const testimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Priya & Rahul Sharma',
    role: 'Wedding Couple',
    content: 'Virendra captured our wedding day beautifully. Every frame felt like a movie. We cry tears of joy every time we watch it. Truly magical work!',
    rating: 5,
  },
  {
    id: '2',
    name: 'Amit Soni',
    role: 'Brand Owner - Soni Enterprises',
    content: 'The promotional video Virendra created for our brand exceeded all expectations. Professional, creative, and delivered ahead of schedule. Highly recommended!',
    rating: 5,
  },
  {
    id: '3',
    name: 'Kavita Joshi',
    role: 'Event Manager',
    content: 'We work with Virendra for all our corporate events. His attention to detail and cinematic eye for storytelling is unmatched in Jabalpur.',
    rating: 5,
  },
  {
    id: '4',
    name: 'Raj Mehra',
    role: 'Restaurant Owner',
    content: 'Our restaurant reels went viral after Virendra shot them! His editing style is just next level. Best investment we made for marketing.',
    rating: 5,
  },
]

export const stats = [
  { value: '150+', label: 'Projects Completed' },
  { value: '5+', label: 'Years Experience' },
  { value: '100%', label: 'Client Satisfaction' },
  { value: '50+', label: 'Happy Clients' },
]

export const tools = [
  { name: 'Adobe Premiere Pro', icon: '🎞️', category: 'Editing' },
  { name: 'Adobe After Effects', icon: '✨', category: 'VFX' },
  { name: 'DaVinci Resolve', icon: '🎨', category: 'Color' },
  { name: 'Adobe Audition', icon: '🎵', category: 'Audio' },
  { name: 'Photoshop', icon: '🖼️', category: 'Design' },
  { name: 'DJI Drone', icon: '🚁', category: 'Aerial' },
  { name: 'Sony A7 IV', icon: '📷', category: 'Camera' },
  { name: 'DJI Ronin', icon: '🎥', category: 'Gimbal' },
]
